version: "3.8"
services:
  postgresDB:
    image: postgres:16.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_cies_symplex
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5436:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: yamilmaytaq@gmail.com
      PGADMIN_DEFAULT_PASSWORD: yamilmaytaq
    ports:
      - "8080:80"
    depends_on:
      - postgresDB
